name: Python CD

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Mock Deploy
        run: |
          echo "Deploying to production server..."
