name: Python CI

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Check code formatting with Black
        run: |
          pip install black
          black --check .
